name=SyncItIOT
version=1.1.0
author=Snow Fox Lab PVT LTD
maintainer=Bikash Adhikari <bikash@snowfoxlab.com.np>
sentence=Official Arduino library for the SyncIt IOT management platform.
paragraph=This library handles secure MQTTS connections, automatic heartbeats, benchmark telemetry, TLS/NON-TLS MQTT communication, and JSON telemetry for the SyncIt ecosystem.
category=Communication
url=https://github.com/snowfoxlab/SyncItIOT
architectures=*
includes=SyncItIOT.h
depends=PubSubClient, ArduinoJson