name=SyncItIOT
version=1.0.0
author=Snow Fox Lab PVT LTD 
maintainer=Bikash Adhikari <bikash@snowfoxlab.com.np>
sentence=Official Arduino library for the SyncIt IOT management platform.
paragraph=This library handles secure MQTTS connections, automatic heartbeats, and JSON telemetry for the SyncIt ecosystem. Optimized for SyncIt IOT Cloud.
category=Communication
url=https://github.com/snowfoxlab/SyncItIOT
architectures=*
includes=SyncItIOT.h
depends=PubSubClient, ArduinoJson(>=7.0.0)
